import "./globals.css";
import { Ubuntu } from 'next/font/google'


const ubuntu = Ubuntu({
  weight: '400',
  subsets: ['latin'],
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
